#!/usr/bin/env python3
"""Convert paired-reading Markdown into TeX macro calls.

Supported source form:

::: pair
zh: Chinese main line
jp: Japanese main line
zh_comment: Chinese note
jp_comment: Japanese note
:::

Lines after a field continue that field until the next field marker.
Headings outside pair blocks are converted to chapters/sections.
Inside fields, TeX is passed through intentionally so ruby macros such
as \zhpy{大}{da4} and \jpruby{大学}{だいがく} can be used directly.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


FIELD_RE = re.compile(r"^(zh|jp|zh_comment|jp_comment)\s*:\s*(.*)$")


def escape_tex(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def braced(text: str) -> str:
    return "{%\n" + text.strip() + "\n}"


def flush_pair(fields: dict[str, str]) -> str:
    for key in ("zh", "jp"):
        if not fields.get(key, "").strip():
            raise ValueError(f"pair block is missing required field {key!r}")
    return "\n".join(
        [
            r"\Pair",
            braced(fields.get("zh", "")),
            braced(fields.get("jp", "")),
            braced(fields.get("zh_comment", "")),
            braced(fields.get("jp_comment", "")),
            "",
        ]
    )


def convert(text: str) -> str:
    output: list[str] = [
        "% Generated by scripts/paired/md_to_tex.py. Edit the Markdown source, not this file.",
        "",
    ]
    in_pair = False
    current_field: str | None = None
    fields: dict[str, str] = {}

    for line_no, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()

        if not in_pair and stripped == "::: pair":
            in_pair = True
            current_field = None
            fields = {"zh": "", "jp": "", "zh_comment": "", "jp_comment": ""}
            continue

        if in_pair and stripped == ":::":
            output.append(flush_pair(fields))
            in_pair = False
            current_field = None
            fields = {}
            continue

        if in_pair:
            match = FIELD_RE.match(line)
            if match:
                current_field = match.group(1)
                fields[current_field] = match.group(2).strip()
            elif current_field is not None:
                if fields[current_field]:
                    fields[current_field] += "\n"
                fields[current_field] += line.rstrip()
            elif stripped:
                raise ValueError(f"line {line_no}: text before first pair field")
            continue

        if stripped.startswith("#"):
            hashes, title = stripped.split(maxsplit=1)
            level = len(hashes)
            title_tex = escape_tex(title.strip())
            if level == 1:
                output.append(rf"\chapter{{{title_tex}}}")
            elif level == 2:
                output.append(rf"\section{{{title_tex}}}")
            elif level == 3:
                output.append(rf"\subsection{{{title_tex}}}")
            else:
                output.append(rf"\paragraph{{{title_tex}}}")
            continue

        if stripped:
            output.append(escape_tex(stripped) + r"\par")
        else:
            output.append("")

    if in_pair:
        raise ValueError("unclosed pair block at end of file")

    return "\n".join(output).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", help="paired Markdown source")
    parser.add_argument("-o", "--output", help="TeX output path; defaults to stdout")
    args = parser.parse_args(argv)

    source = Path(args.source)
    result = convert(source.read_text(encoding="utf-8"))
    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(result, encoding="utf-8")
    else:
        sys.stdout.write(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
