#!/usr/bin/env python3
"""Convert interlinear JSON into Japanese-main / Chinese-comment TeX."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


def tex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def token_role(token: dict[str, str]) -> str:
    return str(token.get("g") or "")


def wrap_role(text: str, role: str) -> str:
    if not role:
        return text
    return rf"\Gram{{{tex_escape(role)}}}{{{text}}}"


def render_tokens(tokens: list[dict[str, str]], ruby_cmd: str, breakable: bool = False) -> str:
    parts: list[str] = []
    for token in tokens:
        raw_text = token.get("t", "")
        text = tex_escape(raw_text)
        ruby = tex_escape(token.get("r", ""))
        role = token_role(token)
        if ruby:
            rendered = rf"\{ruby_cmd}{{{text}}}{{{ruby}}}"
        elif breakable:
            rendered = r"\allowbreak{}".join(tex_escape(ch) for ch in raw_text)
        else:
            rendered = text
        parts.append(wrap_role(rendered, role))
        if breakable:
            parts.append(r"\allowbreak{}")
    return "".join(parts)


def render_ja_lines(unit: dict[str, Any]) -> str:
    lines = unit.get("ja", [])
    tokens: list[dict[str, str]] = []
    for line in lines:
        tokens.extend(line)
    return render_tokens(tokens, "jpruby", breakable=True)


def brace(text: str) -> str:
    if not text:
        return "{}"
    return "{%\n" + text + "\n}"


def emit_unit(unit: dict[str, Any]) -> str:
    ja = render_ja_lines(unit)
    zh = render_tokens(unit["zh"], "zhpy", breakable=True)
    return "\n".join([r"\JpMainUnit", brace(ja), brace(zh), ""])


def convert(
    data: dict[str, Any],
    *,
    author: str,
    curated_by: str,
    curated_url: str,
    powered_by: str,
    cover_image: str,
) -> str:
    title_ja = render_tokens(data["title"]["ja"], "jpruby")
    title_zh = render_tokens(data["title"]["zh"], "zhpy")
    out: list[str] = [
        "% Generated by scripts/interlinear/json_to_jp_main_tex.py. Edit the JSON source, not this file.",
        rf"\JpMainTitle{brace(title_ja)}{brace(title_zh)}{{{tex_escape(author)}}}{{{tex_escape(curated_by)}}}{{{tex_escape(curated_url)}}}{{{tex_escape(powered_by)}}}{{{tex_escape(cover_image)}}}",
        "",
    ]

    for section in data.get("sections", []):
        out.append(
            rf"\JpMainSection{brace(render_tokens(section['title_ja'], 'jpruby'))}{brace(render_tokens(section['title_zh'], 'zhpy'))}"
        )
        for subsection in section.get("subsections", []):
            out.append(
                rf"\JpMainSubsection{brace(render_tokens(subsection['title_ja'], 'jpruby'))}{brace(render_tokens(subsection['title_zh'], 'zhpy'))}"
            )
            for story in subsection.get("stories", []):
                title_ja_story = render_tokens(story["title_ja"], "jpruby")
                title_zh_story = render_tokens(story["title_zh"], "zhpy")
                place_ja = render_tokens(story.get("place_ja", []), "jpruby")
                place_zh = render_tokens(story.get("place_zh", []), "zhpy")
                out.append(
                    rf"\JpMainStory{{{tex_escape(story['id'])}}}{brace(title_ja_story)}{brace(title_zh_story)}{brace(place_ja)}{brace(place_zh)}"
                )
                for paragraph in story.get("paragraphs", []):
                    out.append(r"\JpMainParagraphStart")
                    for unit in paragraph.get("units", []):
                        out.append(emit_unit(unit))
                    out.append(r"\JpMainParagraphEnd")
                    out.append("")

    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", help="interlinear JSON source")
    parser.add_argument("-o", "--output", help="TeX output path; defaults to stdout")
    parser.add_argument("--author", default="夏目漱石")
    parser.add_argument("--curated-by", default="AgInTiFlow curated")
    parser.add_argument("--curated-url", default="https://flow.lazying.art")
    parser.add_argument("--powered-by", default="powered by LazyingArt")
    parser.add_argument("--cover-image", default="")
    args = parser.parse_args(argv)

    source = Path(args.source)
    data = json.loads(source.read_text(encoding="utf-8"))
    result = convert(
        data,
        author=args.author,
        curated_by=args.curated_by,
        curated_url=args.curated_url,
        powered_by=args.powered_by,
        cover_image=args.cover_image,
    )
    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(result, encoding="utf-8")
    else:
        sys.stdout.write(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
