#!/usr/bin/env python3
"""Render Arabic-spine quadrilingual Quran JSON as TeX."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from json_to_trilingual_pair_tex import (
    brace,
    optional_arg_text,
    short_toc_title,
    tex_escape,
    tex_escape_en,
    tex_path_arg,
    token_text,
    wrap_role,
)


LAYER_LANG = {"ar": "ar", "en": "en", "ja": "ja", "zh": "zh"}
LAYER_LABELS = {"ar": "AR", "en": "EN", "ja": "日", "zh": "中"}
LAYER_NAMES = {
    "ar": "Arabic",
    "en": "English",
    "ja": "日本語",
    "zh": "中文",
}
MAIN_MACRO = {
    "ar": "QuranMainAr",
    "en": "QuranMainEn",
    "ja": "QuranMainJa",
    "zh": "QuranMainZh",
}
NOTE_MACRO = {
    "ar": "QuranNoteAr",
    "en": "QuranNoteEn",
    "ja": "QuranNoteJa",
    "zh": "QuranNoteZh",
}
DEFAULT_NOTE_ORDER = {
    "ar": ["en", "ja", "zh"],
    "en": ["ar", "ja", "zh"],
    "ja": ["ar", "en", "zh"],
    "zh": ["ar", "en", "ja"],
}


def render_ar_tokens(tokens: list[dict[str, Any]]) -> str:
    parts: list[str] = []
    for token in tokens:
        raw_text = str(token.get("t", ""))
        text = tex_escape(raw_text)
        ruby = tex_escape(str(token.get("r", "")))
        rendered = rf"\ArRuby{{{text}}}{{{ruby}}}" if ruby else rf"\ArWord{{{text}}}"
        parts.append(wrap_role(rendered, str(token.get("g") or "")))
        parts.append(r"\ArSpace{}")
    return "".join(parts)


def render_tokens(tokens: list[dict[str, Any]], lang: str) -> str:
    if lang == "ar":
        return render_ar_tokens(tokens)
    parts: list[str] = []
    for token in tokens:
        raw_text = str(token.get("t", ""))
        text = tex_escape_en(raw_text) if lang == "en" else tex_escape(raw_text)
        ruby = tex_escape(str(token.get("r", "")))
        role = str(token.get("g") or "")
        if lang == "zh" and ruby:
            rendered = rf"\zhpy{{{text}}}{{{ruby}}}"
        elif lang == "ja" and ruby:
            rendered = rf"\jpruby{{{text}}}{{{ruby}}}"
        else:
            rendered = text
        parts.append(wrap_role(rendered, role))
        parts.append(r"\allowbreak{}")
    return "".join(parts)


def render_layer(tokens: list[dict[str, Any]], layer: str, kind: str) -> str:
    rendered = render_tokens(tokens, LAYER_LANG[layer])
    macro = MAIN_MACRO[layer] if kind == "main" else NOTE_MACRO[layer]
    return rf"\{macro}{{{rendered}}}"


def plain_title(data: dict[str, Any], layer: str) -> str:
    return token_text(data.get("title", {}).get(layer, []))


def toc_title_for_chapter(chapter_title: dict[str, Any], main_layer: str) -> str:
    """Use a font-safe short title for the printed/PDF TOC.

    The actual chapter heading may be Arabic. The ToC line, however, is written
    through LaTeX's auxiliary file and is more robust with LTR Latin/CJK text
    unless every ToC context is wrapped in an Arabic font.
    """
    if main_layer == "ar":
        return token_text(chapter_title.get("en", [])) or token_text(chapter_title.get("zh", []))
    return token_text(chapter_title.get(main_layer, []))


def convert(
    data: dict[str, Any],
    *,
    main_layer: str,
    note_order: list[str] | None,
    color_mode: str,
    curated_by: str,
    curated_url: str,
    powered_by: str,
    cover_image: str,
) -> str:
    note_layers = note_order or DEFAULT_NOTE_ORDER[main_layer]
    for layer in note_layers:
        if layer not in LAYER_LANG:
            raise ValueError(f"unknown note layer: {layer}")
        if layer == main_layer:
            raise ValueError(f"note order cannot include main layer: {layer}")
    title = data.get("title", {})
    main_title = render_layer(title.get(main_layer, []), main_layer, "main")
    subtitle = " / ".join(render_layer(title.get(layer, []), layer, "note") for layer in note_layers)
    layer_text = f"{LAYER_NAMES[main_layer]} main / " + " + ".join(LAYER_NAMES[layer] for layer in note_layers)
    out: list[str] = [
        "% Generated by scripts/interlinear/json_to_arabic_quadrilingual_tex.py. Edit JSON, not this file.",
    ]
    if color_mode == "blackwhite":
        out.append(r"\BlackWhiteMode")
    out.extend(
        [
            rf"\QuranPdfMeta{{{tex_escape(plain_title(data, main_layer))}}}{{LinguaLeaf}}",
            rf"\QuranTitle{brace(main_title)}{brace(subtitle)}{{{tex_escape(layer_text)}}}{{{tex_escape(curated_by)}}}{{{tex_escape(curated_url)}}}{{{tex_escape(powered_by)}}}{{{tex_path_arg(cover_image)}}}",
            "",
        ]
    )
    for chapter in data.get("chapters", []):
        chapter_title = chapter.get("title", {})
        main_chapter = render_layer(chapter_title.get(main_layer, []), main_layer, "main")
        chapter_subtitle = " / ".join(render_layer(chapter_title.get(layer, []), layer, "note") for layer in note_layers)
        toc_title = optional_arg_text(short_toc_title(toc_title_for_chapter(chapter_title, main_layer)))
        number = str(chapter.get("number") or "")
        out.append(rf"\QuranChapter{{{tex_escape(number)}}}{brace(main_chapter)}{brace(chapter_subtitle)}[{toc_title}]")
        for paragraph in chapter.get("paragraphs", []):
            out.append(r"\QuranParagraphStart")
            for unit in paragraph.get("units", []):
                main = render_layer(unit.get(main_layer, []), main_layer, "main")
                notes: list[str] = []
                for layer in note_layers:
                    notes.append(rf"{{{tex_escape(LAYER_LABELS[layer])}}}")
                    notes.append(brace(render_layer(unit.get(layer, []), layer, "note")))
                verse_key = str(unit.get("verse_key") or "")
                out.append("\n".join([r"\QuranUnit", f"{{{tex_escape(verse_key)}}}", brace(main), *notes, ""]))
            out.append(r"\QuranParagraphEnd")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source")
    parser.add_argument("-o", "--output")
    parser.add_argument("--main-layer", choices=list(LAYER_LANG), default="ar")
    parser.add_argument("--note-order", default="")
    parser.add_argument("--color-mode", choices=["color", "blackwhite"], default="color")
    parser.add_argument("--curated-by", default="AgInTiFlow curated")
    parser.add_argument("--curated-url", default="https://flow.lazying.art")
    parser.add_argument("--powered-by", default="powered by LazyingArt")
    parser.add_argument("--cover-image", default="")
    args = parser.parse_args(argv)
    data = json.loads(Path(args.source).read_text(encoding="utf-8"))
    note_order = [part.strip() for part in args.note_order.split(",") if part.strip()] or None
    result = convert(
        data,
        main_layer=args.main_layer,
        note_order=note_order,
        color_mode=args.color_mode,
        curated_by=args.curated_by,
        curated_url=args.curated_url,
        powered_by=args.powered_by,
        cover_image=args.cover_image,
    )
    if args.output:
        path = Path(args.output)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(result, encoding="utf-8")
    else:
        sys.stdout.write(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
