#!/usr/bin/env python3
"""Render quadrilingual wenyan-main JSON as TeX source."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from json_to_trilingual_pair_tex import (
    brace,
    render_author,
    render_tokens,
    tex_escape,
    tex_path_arg,
    token_text,
)


LAYER_LANG = {
    "wenyan": "zh",
    "zh_modern": "zh",
    "ja_modern": "ja",
    "en": "en",
}
LAYER_LABELS = {
    "wenyan": "文",
    "zh_modern": "今中",
    "ja_modern": "日",
    "en": "EN",
}
LAYER_NAMES = {
    "wenyan": "Wenyan",
    "zh_modern": "Modern Chinese",
    "ja_modern": "Modern Japanese",
    "en": "English",
}
MAIN_MACRO = {
    "wenyan": "QuadMainWenyan",
    "zh_modern": "QuadMainZhModern",
    "ja_modern": "QuadMainJaModern",
    "en": "QuadMainEn",
}
NOTE_MACRO = {
    "wenyan": "QuadNoteWenyan",
    "zh_modern": "QuadNoteZhModern",
    "ja_modern": "QuadNoteJaModern",
    "en": "QuadNoteEn",
}
DEFAULT_NOTE_ORDER = {
    "wenyan": ["zh_modern", "ja_modern", "en"],
    "zh_modern": ["wenyan", "ja_modern", "en"],
    "ja_modern": ["wenyan", "zh_modern", "en"],
    "en": ["wenyan", "zh_modern", "ja_modern"],
}


def render_layer(tokens: list[dict[str, Any]], layer: str, kind: str) -> str:
    lang = LAYER_LANG[layer]
    rendered = render_tokens(tokens, lang)
    macro = MAIN_MACRO[layer] if kind == "main" else NOTE_MACRO[layer]
    return rf"\{macro}{{{rendered}}}"


def main_plain(data: dict[str, Any], layer: str) -> str:
    return token_text(data.get("title", {}).get(layer, []))


def convert(
    data: dict[str, Any],
    *,
    main_layer: str,
    color_mode: str,
    author: str,
    author_reading: str,
    curated_by: str,
    curated_url: str,
    powered_by: str,
    cover_image: str,
) -> str:
    note_layers = DEFAULT_NOTE_ORDER[main_layer]
    title = data.get("title", {})
    main_title = render_layer(title.get(main_layer, []), main_layer, "main")
    subtitle = " / ".join(render_layer(title.get(layer, []), layer, "note") for layer in note_layers)
    layer_text = f"{LAYER_NAMES[main_layer]} main / " + " + ".join(LAYER_NAMES[layer] for layer in note_layers) + " notes"
    out: list[str] = [
        "% Generated by scripts/interlinear/json_to_quadrilingual_wenyan_tex.py. Edit JSON, not this file.",
    ]
    if color_mode == "blackwhite":
        out.append(r"\BlackWhiteMode")
    out.extend(
        [
            rf"\QuadPdfMeta{{{tex_escape(main_plain(data, main_layer))}}}{{{tex_escape(author)}}}",
            rf"\QuadTitle{brace(main_title)}{brace(subtitle)}{{{tex_escape(layer_text)}}}{{{render_author(author, author_reading)}}}{{{tex_escape(curated_by)}}}{{{tex_escape(curated_url)}}}{{{tex_escape(powered_by)}}}{{{tex_path_arg(cover_image)}}}",
            "",
        ]
    )
    for chapter in data.get("chapters", []):
        chapter_title = chapter.get("title", {})
        main_chapter = render_layer(chapter_title.get(main_layer, []), main_layer, "main")
        chapter_subtitle = " / ".join(render_layer(chapter_title.get(layer, []), layer, "note") for layer in note_layers)
        number = str(chapter.get("number") or "")
        out.append(rf"\QuadChapter{{{tex_escape(number)}}}{brace(main_chapter)}{brace(chapter_subtitle)}")
        for paragraph in chapter.get("paragraphs", []):
            out.append(r"\QuadParagraphStart")
            for unit in paragraph.get("units", []):
                main = render_layer(unit.get(main_layer, []), main_layer, "main")
                notes: list[str] = []
                for layer in note_layers:
                    notes.append(rf"{{{tex_escape(LAYER_LABELS[layer])}}}")
                    notes.append(brace(render_layer(unit.get(layer, []), layer, "note")))
                out.append("\n".join([r"\QuadUnit", brace(main), *notes, ""]))
            out.append(r"\QuadParagraphEnd")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source")
    parser.add_argument("-o", "--output")
    parser.add_argument("--main-layer", choices=list(LAYER_LANG), default="wenyan")
    parser.add_argument("--color-mode", choices=["color", "blackwhite"], default="color")
    parser.add_argument("--author", default="")
    parser.add_argument("--author-reading", default="")
    parser.add_argument("--curated-by", default="AgInTiFlow curated")
    parser.add_argument("--curated-url", default="https://flow.lazying.art")
    parser.add_argument("--powered-by", default="powered by LazyingArt")
    parser.add_argument("--cover-image", default="")
    args = parser.parse_args(argv)
    data = json.loads(Path(args.source).read_text(encoding="utf-8"))
    result = convert(
        data,
        main_layer=args.main_layer,
        color_mode=args.color_mode,
        author=args.author,
        author_reading=args.author_reading,
        curated_by=args.curated_by,
        curated_url=args.curated_url,
        powered_by=args.powered_by,
        cover_image=args.cover_image,
    )
    if args.output:
        path = Path(args.output)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(result, encoding="utf-8")
    else:
        sys.stdout.write(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
