#!/usr/bin/env python3
"""Render trilingual JSON as English main text with indented Japanese and Chinese notes."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from json_to_trilingual_pair_tex import (
    brace,
    optional_arg_text,
    render_author,
    render_lang,
    short_toc_title,
    tex_escape,
    tex_path_arg,
    token_text,
)


def convert(
    data: dict[str, Any],
    *,
    color_mode: str,
    author: str,
    author_reading: str,
    curated_by: str,
    curated_url: str,
    powered_by: str,
    cover_image: str,
) -> str:
    title = data.get("title", {})
    title_en_plain = token_text(title.get("en", []))
    title_en = render_lang(title.get("en", []), "en", "main")
    title_ja = render_lang(title.get("ja", []), "ja", "comment")
    title_zh = render_lang(title.get("zh", []), "zh", "comment")

    out: list[str] = [
        "% Generated by scripts/interlinear/json_to_trilingual_en_notes_tex.py. Edit JSON, not this file.",
        r"\renewcommand{\contentsname}{Contents}",
    ]
    if color_mode == "blackwhite":
        out.append(r"\BlackWhiteMode")
    out.extend(
        [
            rf"\TriAllPdfMeta{{{tex_escape(title_en_plain)}}}{{{tex_escape(author)}}}",
            rf"\TriAllTitle{brace(title_en)}{brace(title_ja)}{brace(title_zh)}{{{render_author(author, author_reading)}}}{{{tex_escape(curated_by)}}}{{{tex_escape(curated_url)}}}{{{tex_escape(powered_by)}}}{{{tex_path_arg(cover_image)}}}",
            "",
        ]
    )

    for chapter in data.get("chapters", []):
        chapter_title = chapter.get("title", {})
        en_chapter = render_lang(chapter_title.get("en", []), "en", "main")
        ja_chapter = render_lang(chapter_title.get("ja", []), "ja", "comment")
        zh_chapter = render_lang(chapter_title.get("zh", []), "zh", "comment")
        toc_title = short_toc_title(
            token_text(chapter_title.get("en", []))
            or token_text(chapter_title.get("ja", []))
            or token_text(chapter_title.get("zh", []))
        )
        number = str(chapter.get("number") or "")
        out.append(
            rf"\TriAllChapter{{{tex_escape(number)}}}{brace(en_chapter)}{brace(ja_chapter)}{brace(zh_chapter)}[{optional_arg_text(toc_title)}]"
        )
        for paragraph in chapter.get("paragraphs", []):
            out.append(r"\TriAllParagraphStart")
            for unit in paragraph.get("units", []):
                en = render_lang(unit.get("en", []), "en", "main")
                ja = render_lang(unit.get("ja", []), "ja", "comment")
                zh = render_lang(unit.get("zh", []), "zh", "comment")
                out.append("\n".join([r"\TriAllUnit", brace(en), brace(ja), brace(zh), ""]))
            out.append(r"\TriAllParagraphEnd")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source")
    parser.add_argument("-o", "--output")
    parser.add_argument("--color-mode", choices=["color", "blackwhite"], default="color")
    parser.add_argument("--author", default="")
    parser.add_argument("--author-reading", default="")
    parser.add_argument("--curated-by", default="AgInTiFlow curated")
    parser.add_argument("--curated-url", default="https://flow.lazying.art")
    parser.add_argument("--powered-by", default="powered by LazyingArt")
    parser.add_argument("--cover-image", default="")
    args = parser.parse_args(argv)

    data = json.loads(Path(args.source).read_text(encoding="utf-8"))
    result = convert(
        data,
        color_mode=args.color_mode,
        author=args.author,
        author_reading=args.author_reading,
        curated_by=args.curated_by,
        curated_url=args.curated_url,
        powered_by=args.powered_by,
        cover_image=args.cover_image,
    )
    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(result, encoding="utf-8")
    else:
        sys.stdout.write(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
