#!/usr/bin/env python3
"""Convert the interlinear JSON corpus into run-in TeX macro calls."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


def tex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def render_tokens(tokens: list[dict[str, str]], ruby_cmd: str, breakable: bool = False) -> str:
    parts: list[str] = []
    for token in tokens:
        text = tex_escape(token.get("t", ""))
        ruby = tex_escape(token.get("r", ""))
        if ruby:
            parts.append(rf"\{ruby_cmd}{{{text}}}{{{ruby}}}")
        else:
            parts.append(text)
        if breakable:
            parts.append(r"\allowbreak{}")
    return "".join(parts)


def brace(text: str) -> str:
    if not text:
        return "{}"
    return "{%\n" + text + "\n}"


def emit_unit(unit: dict[str, Any]) -> str:
    zh = render_tokens(unit["zh"], "zhpy", breakable=True)
    ja_lines = unit.get("ja", [])
    ja1 = render_tokens(ja_lines[0], "jpruby", breakable=True) if len(ja_lines) > 0 else ""
    ja2 = render_tokens(ja_lines[1], "jpruby", breakable=True) if len(ja_lines) > 1 else ""
    return "\n".join([r"\RunUnit", brace(zh), brace(ja1), brace(ja2), ""])


def convert(data: dict[str, Any]) -> str:
    out: list[str] = [
        "% Generated by scripts/interlinear/json_to_run_tex.py. Edit the JSON source, not this file.",
        rf"\RunTitle{brace(render_tokens(data['title']['zh'], 'zhpy'))}{brace(render_tokens(data['title']['ja'], 'jpruby'))}",
        "",
    ]

    for section in data.get("sections", []):
        out.append(
            rf"\RunSection{brace(render_tokens(section['title_zh'], 'zhpy'))}{brace(render_tokens(section['title_ja'], 'jpruby'))}"
        )
        for subsection in section.get("subsections", []):
            out.append(
                rf"\RunSubsection{brace(render_tokens(subsection['title_zh'], 'zhpy'))}{brace(render_tokens(subsection['title_ja'], 'jpruby'))}"
            )
            for story in subsection.get("stories", []):
                title_zh = render_tokens(story["title_zh"], "zhpy")
                title_ja = render_tokens(story["title_ja"], "jpruby")
                place_zh = render_tokens(story.get("place_zh", []), "zhpy")
                place_ja = render_tokens(story.get("place_ja", []), "jpruby")
                out.append(rf"\RunStory{{{tex_escape(story['id'])}}}{brace(title_zh)}{brace(title_ja)}{brace(place_zh)}{brace(place_ja)}")
                for paragraph in story.get("paragraphs", []):
                    out.append(r"\RunParagraphStart")
                    for unit in paragraph.get("units", []):
                        out.append(emit_unit(unit))
                    out.append(r"\RunParagraphEnd")
                    out.append("")

    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", help="interlinear JSON source")
    parser.add_argument("-o", "--output", help="TeX output path; defaults to stdout")
    args = parser.parse_args(argv)

    source = Path(args.source)
    data = json.loads(source.read_text(encoding="utf-8"))
    result = convert(data)
    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(result, encoding="utf-8")
    else:
        sys.stdout.write(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
