#!/usr/bin/env python3
"""Render quadrilingual wenyan-main JSON with Zizhi comment-aware spans."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from json_to_quadrilingual_wenyan_tex import (
    DEFAULT_NOTE_ORDER,
    LAYER_LABELS,
    LAYER_LANG,
    LAYER_NAMES,
    main_plain,
    render_layer,
)
from json_to_trilingual_pair_tex import (
    brace,
    optional_arg_text,
    render_author,
    render_tokens,
    short_toc_title,
    tex_escape,
    tex_path_arg,
)
from zizhi_tongjian_comment_layer import MAIN, json_to_spans, sidecar_key


COMMENT_MACRO = {
    "comment": "QuadMainWenyanComment",
    "pronunciation": "QuadMainWenyanPronunciation",
    "main": "QuadMainWenyan",
}


def load_sidecar(path: str) -> dict[str, list[dict[str, Any]]]:
    if not path:
        return {}
    result: dict[str, list[dict[str, Any]]] = {}
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        record = json.loads(line)
        result[str(record["key"])] = record.get("spans", [])
    return result


def split_tokens_by_char_offsets(
    tokens: list[dict[str, Any]],
    start: int,
    end: int,
) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    offset = 0
    for token in tokens:
        text = str(token.get("t", ""))
        token_start = offset
        token_end = offset + len(text)
        offset = token_end
        if token_end <= start or token_start >= end:
            continue
        piece_start = max(start, token_start) - token_start
        piece_end = min(end, token_end) - token_start
        if piece_start == 0 and piece_end == len(text):
            result.append(token)
            continue
        piece = text[piece_start:piece_end]
        if not piece:
            continue
        split_token = {key: value for key, value in token.items() if key != "r"}
        split_token["t"] = piece
        result.append(split_token)
    return result


def render_zh_tokens_with_ruby_no_grammar(tokens: list[dict[str, Any]]) -> str:
    """Render annotation text with pinyin, but without grammar colors."""
    stripped_tokens = [{key: value for key, value in token.items() if key != "g"} for token in tokens]
    return render_tokens(stripped_tokens, "zh")


def render_wenyan_with_spans(unit: dict[str, Any], span_items: list[dict[str, Any]]) -> str:
    tokens = unit.get("wenyan", [])
    if not isinstance(tokens, list):
        tokens = []
    source_text = str(unit.get("source_wenyan", ""))
    if not span_items:
        return render_layer(tokens, "wenyan", "main")
    parts: list[str] = []
    for span in json_to_spans(span_items):
        if span.start >= span.end:
            continue
        kind = span.kind if span.kind in COMMENT_MACRO else MAIN
        macro = COMMENT_MACRO[kind]
        sub_tokens = split_tokens_by_char_offsets(tokens, span.start, span.end)
        if kind == MAIN:
            rendered = render_tokens(sub_tokens, "zh")
        else:
            rendered = render_zh_tokens_with_ruby_no_grammar(sub_tokens)
        parts.append(rf"\{macro}{{{rendered}}}")
    if not parts:
        return render_layer(tokens, "wenyan", "main")
    # Guard against token/source offset mistakes. If offsets cover too little,
    # append the visible source text as a diagnostic rather than silently drop it.
    covered = "".join(source_text[int(item["start"]) : int(item["end"])] for item in span_items)
    if covered != source_text:
        return render_layer(tokens, "wenyan", "main")
    return "".join(parts)


def convert(
    data: dict[str, Any],
    *,
    main_layer: str,
    note_order: list[str] | None,
    color_mode: str,
    author: str,
    author_reading: str,
    curated_by: str,
    curated_url: str,
    powered_by: str,
    cover_image: str,
    sidecar: dict[str, list[dict[str, Any]]],
) -> str:
    note_layers = note_order or DEFAULT_NOTE_ORDER[main_layer]
    for layer in note_layers:
        if layer not in LAYER_LANG:
            raise ValueError(f"unknown note layer: {layer}")
        if layer == main_layer:
            raise ValueError(f"note order cannot include main layer: {layer}")
    title = data.get("title", {})
    main_title = render_layer(title.get(main_layer, []), main_layer, "main")
    subtitle = " / ".join(render_layer(title.get(layer, []), layer, "note") for layer in note_layers)
    layer_text = f"{LAYER_NAMES[main_layer]} main / " + " + ".join(LAYER_NAMES[layer] for layer in note_layers) + " notes"
    out: list[str] = [
        "% Generated by scripts/interlinear/json_to_quadrilingual_wenyan_comment_aware_tex.py. Edit JSON, not this file.",
    ]
    if color_mode == "blackwhite":
        out.append(r"\BlackWhiteMode")
    out.extend(
        [
            rf"\QuadPdfMeta{{{tex_escape(main_plain(data, main_layer))}}}{{{tex_escape(author)}}}",
            rf"\QuadTitle{brace(main_title)}{brace(subtitle)}{{{tex_escape(layer_text)}}}{{{render_author(author, author_reading)}}}{{{tex_escape(curated_by)}}}{{{tex_escape(curated_url)}}}{{{tex_escape(powered_by)}}}{{{tex_path_arg(cover_image)}}}",
            "",
        ]
    )
    for chapter in data.get("chapters", []):
        chapter_title = chapter.get("title", {})
        main_chapter = render_layer(chapter_title.get(main_layer, []), main_layer, "main")
        chapter_subtitle = " / ".join(render_layer(chapter_title.get(layer, []), layer, "note") for layer in note_layers)
        toc_title = optional_arg_text(short_toc_title(main_plain({"title": chapter_title}, main_layer)))
        number = str(chapter.get("number") or "")
        out.append(rf"\QuadChapter{{{tex_escape(number)}}}{brace(main_chapter)}{brace(chapter_subtitle)}[{toc_title}]")
        for paragraph in chapter.get("paragraphs", []):
            out.append(r"\QuadParagraphStart")
            for unit_index, unit in enumerate(paragraph.get("units", [])):
                if main_layer == "wenyan":
                    key = sidecar_key(str(paragraph.get("id", "")), unit_index)
                    main = render_wenyan_with_spans(unit, sidecar.get(key, []))
                else:
                    main = render_layer(unit.get(main_layer, []), main_layer, "main")
                notes: list[str] = []
                for layer in note_layers:
                    notes.append(rf"{{{tex_escape(LAYER_LABELS[layer])}}}")
                    notes.append(brace(render_layer(unit.get(layer, []), layer, "note")))
                out.append("\n".join([r"\QuadUnit", brace(main), *notes, ""]))
            out.append(r"\QuadParagraphEnd")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source")
    parser.add_argument("-o", "--output")
    parser.add_argument("--main-layer", choices=list(LAYER_LANG), default="wenyan")
    parser.add_argument("--note-order", default="")
    parser.add_argument("--color-mode", choices=["color", "blackwhite"], default="color")
    parser.add_argument("--author", default="")
    parser.add_argument("--author-reading", default="")
    parser.add_argument("--curated-by", default="AgInTiFlow curated")
    parser.add_argument("--curated-url", default="https://flow.lazying.art")
    parser.add_argument("--powered-by", default="powered by LazyingArt")
    parser.add_argument("--cover-image", default="")
    parser.add_argument("--comment-sidecar", default="")
    args = parser.parse_args(argv)
    data = json.loads(Path(args.source).read_text(encoding="utf-8"))
    note_order = [part.strip() for part in args.note_order.split(",") if part.strip()] or None
    result = convert(
        data,
        main_layer=args.main_layer,
        note_order=note_order,
        color_mode=args.color_mode,
        author=args.author,
        author_reading=args.author_reading,
        curated_by=args.curated_by,
        curated_url=args.curated_url,
        powered_by=args.powered_by,
        cover_image=args.cover_image,
        sidecar=load_sidecar(args.comment_sidecar),
    )
    if args.output:
        path = Path(args.output)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(result, encoding="utf-8")
    else:
        sys.stdout.write(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
